# 数据集参数
dataset_config:
  # 图片尺寸(h, w)
  img_size:
    - 512
    - 1024
  #　数据集根目录
  root: /home/lacker/work/Dataset/cityscapes
  # 训练数据列表文件
  trainset_file: data/train.list
  # 验证数据列表文件
  valset_file: data/val.list
  # 测试数据列表文件
  testset_file: data/test.list

# 训练参数
train_config:
  # 训练轮数
  num_epochs: 10
  # 训练批大小
  batch_size: 4
  # 学习率
  learning_rate: 0.001
  # stage3、stage4、stage5的次数
  num_stage:
    - 4
    - 5
    - 3
  # use_boundary
  use_boundary_2: False
  use_boundary_4: False
  use_boundary_8: True
  use_boundary_16: False



