# 数据集参数
dataset_config:
  # 图片尺寸(h, w)
  img_size:
    - 512
    - 1024
  #　数据集根目录
  root: /home/lacker/work/Dataset/cityscapes
  # 训练数据列表文件
  trainset_file: /home/lacker/work/Dataset/cityscapes/train.list
  # 验证数据列表文件
  valset_file: /home/lacker/work/Dataset/cityscapes/val.list
  # 测试数据列表文件
  testset_file: /home/lacker/work/Dataset/cityscapes/test.list

# 训练参数
train_config:
  # 模型参数存放路径
  params_dir: ./inferences
  # 持续上一次模型参数训练
  continue_train: False
  # 读取的模型参数路径
  load_params: ./inferences/model_maxmIOU50_1.1.pdparams
  # 分类数
  n_classes: 19
  # 训练轮数
  num_epochs: 10
  # 训练批大小
  batch_size: 4
  # stage3、stage4、stage5的次数
  num_stage:
    - 4
    - 5
    - 3
  # use_boundary
  use_boundary_2: False
  use_boundary_4: False
  use_boundary_8: True
  # 学习率配置
  opt_config:
    learning_rate: 0.01
    boundaries:
      - 1
      - 3
      - 8
      - 15
      - 20
      - 30
      - 40
      - 50
      - 70
    values:
      - 1
      - 0.666
      - 0.333
      - 0.1
      - 0.0666
      - 0.0333
      - 0.01
      - 0.00666
      - 0.00333
      - 0.001
