# 数据集参数
dataset_config:
  # 图片尺寸
  img_size: 224

# 训练参数
train_config:
  # 训练轮数
  num_epochs: 10
  # 训练批大小
  batch_size: 4
  # 学习率
  learning_rate: 0.001
  # stage3、stage4、stage5的次数
  num_stage:
    - 3
    - 3
    - 3
